name: maggom-api

services:
  app:
    image: ghcr.io/ma-ggom/api:latest
    container_name: maggom-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
      SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ../logs/spring:/logs
    restart: always