FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY app/build/libs/app.jar app.jar
COPY app/config/ config/
ENTRYPOINT ["java", "-Xmx256m", "-XX:MaxMetaspaceSize=112m", "-XX:ReservedCodeCacheSize=48m", "-Xss512k", "-XX:+UseSerialGC", "-jar", "app.jar"]
